# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Queer Kahani
email: sumu.tasib@gmail.com
description: "Queer Kahani is a quirky and curious podcast of bite-sized queer stories told in an interactive interview format - happy stories, sad stories, coming out stories, closing in stories, first loves, worst loves, epiphanies, recipes, and everything in between."
subtitle: "A place for queer stories"
lang: en-us
author: Sumu Tasib
copyright: "&#xA9; 2021"

# URL settings (choose remote or local)
# remote settings
baseurl: "/podcast" # the subpath of your site, e.g. /blog
url: "https://queerkahani.com" # the base hostname & protocol for your site
# local (development) settings
# baseurl: "file:///C:/git/sumutasib/sumutasib.github.io/podcast" # the subpath of your site, e.g. /blog
# url: "http://sumutasib.github.io" # the base hostname & protocol for your site

twitter_username: sumutasib
github_username:  sumutasib

permalink: /episodes/:title.html

#Timezone
timezone: America/Los_Angeles

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

# Output to ../podcast
destination: "../podcast"

#Exclude local build settings
exclude: ['plyr-test.html', 'readme.md', 'Gemfile.lock', 'Gemfile']
